import Image from "next/image";

/**
 * A book jacket. Every cover is an SVG generated by
 * scripts/generate-covers.mjs, already smaller than any raster the image
 * optimiser could produce. Routing it through /_next/image would only cost a
 * round trip — and require `dangerouslyAllowSVG` site-wide — so it is served
 * straight from /public instead.
 */
export default function BookCover({
  src,
  alt,
  className = "",
  priority = false,
  eager = false,
  sizes,
}: {
  src: string;
  alt: string;
  className?: string;
  priority?: boolean;
  eager?: boolean;
  sizes?: string;
}) {
  return (
    <Image
      src={src}
      alt={alt}
      width={600}
      height={900}
      unoptimized
      priority={priority}
      loading={eager && !priority ? "eager" : undefined}
      sizes={sizes}
      className={className}
    />
  );
}
