import Image from "next/image";

/**
 * A book jacket.
 *
 * Every cover in this catalogue is an SVG generated by
 * scripts/generate-covers.mjs, so it is already smaller than any raster the
 * image optimiser could produce and scales losslessly to any size. Routing it
 * through /_next/image would only cost a round trip — and would mean turning on
 * `dangerouslyAllowSVG` for the whole site — so every jacket is served straight
 * from /public instead.
 */
export default function BookCover({
  src,
  alt,
  className = "",
  priority = false,
  eager = false,
  sizes,
}: {
  src: string;
  alt: string;
  className?: string;
  priority?: boolean;
  /** Set on jackets that are client-rendered after hydration (basket, checkout). */
  eager?: boolean;
  sizes?: string;
}) {
  return (
    <Image
      src={src}
      alt={alt}
      width={600}
      height={900}
      unoptimized
      priority={priority}
      loading={eager && !priority ? "eager" : undefined}
      sizes={sizes}
      className={className}
    />
  );
}
